name: nencarta_py312
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - beautifulsoup4
  - cython
  - dask
  - dataretrieval
  - fiona
  - gdal
  - geoglows
  - geojson
  - geopandas
  - netcdf4
  - numba
  - numpy
  - pandas
  - pillow
  - proj-data
  - progress
  - pyproj
  - pyqt>=5.15
  - rasterio
  - requests
  - s3fs
  - scipy
  - shapely
  - tqdm
  - xarray<2025.4.0
  - whitebox
  - zarr